org.gradle.jvmargs=-Xmx2048m -XX\:+HeapDumpOnOutOfMemoryError \
  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
  --add-opens=java.base/java.io=ALL-UNNAMED \
  --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
org.gradle.caching=true
org.gradle.parallel=true
kotlin.parallel.tasks.in.project=true
android.enableR8.fullMode=true
org.gradle.configuration-cache=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
