package cz.kutner.comicsdb.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFFC00000)
val OnPrimary = Color.White
val Secondary = Color(0xFF009688)
val OnSecondary = Color.White
val HeaderTextColor = Color(0xFF808080)

val md_primary_light = Color(0xFFC00000)
val md_on_primary_light = Color(0xFFFFFFFF)
val md_primary_container_light = Color(0xFFFFDAD5)
val md_on_primary_container_light = Color(0xFF410000)
val md_secondary_light = Color(0xFF006A60)
val md_on_secondary_light = Color(0xFFFFFFFF)
val md_secondary_container_light = Color(0xFF74F8E6)
val md_on_secondary_container_light = Color(0xFF00201C)
val md_tertiary_light = Color(0xFF775652)
val md_on_tertiary_light = Color(0xFFFFFFFF)
val md_tertiary_container_light = Color(0xFFFFDAD5)
val md_on_tertiary_container_light = Color(0xFF2C1512)
val md_error_light = Color(0xFFBA1A1A)
val md_on_error_light = Color(0xFFFFFFFF)
val md_error_container_light = Color(0xFFFFDAD6)
val md_on_error_container_light = Color(0xFF410002)
val md_background_light = Color(0xFFFFFBFF)
val md_on_background_light = Color(0xFF201A19)
val md_surface_light = Color(0xFFFFFBFF)
val md_on_surface_light = Color(0xFF201A19)
val md_surface_variant_light = Color(0xFFF5DDD9)
val md_on_surface_variant_light = Color(0xFF534341)
val md_outline_light = Color(0xFF857371)
val md_outline_variant_light = Color(0xFFD8C2BE)
val md_inverse_primary_light = Color(0xFFFFB4AB)

val md_primary_dark = Color(0xFFFFB4AB)
val md_on_primary_dark = Color(0xFF690000)
val md_primary_container_dark = Color(0xFF930006)
val md_on_primary_container_dark = Color(0xFFFFDAD5)
val md_secondary_dark = Color(0xFF53DBCA)
val md_on_secondary_dark = Color(0xFF003731)
val md_secondary_container_dark = Color(0xFF005048)
val md_on_secondary_container_dark = Color(0xFF74F8E6)
val md_tertiary_dark = Color(0xFFE7BDB7)
val md_on_tertiary_dark = Color(0xFF442926)
val md_tertiary_container_dark = Color(0xFF5D3F3B)
val md_on_tertiary_container_dark = Color(0xFFFFDAD5)
val md_error_dark = Color(0xFFFFB4AB)
val md_on_error_dark = Color(0xFF690005)
val md_error_container_dark = Color(0xFF93000A)
val md_on_error_container_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF201A19)
val md_on_background_dark = Color(0xFFEDE0DE)
val md_surface_dark = Color(0xFF201A19)
val md_on_surface_dark = Color(0xFFEDE0DE)
val md_surface_variant_dark = Color(0xFF534341)
val md_on_surface_variant_dark = Color(0xFFD8C2BE)
val md_outline_dark = Color(0xFFA08C8A)
val md_outline_variant_dark = Color(0xFF534341)
val md_inverse_primary_dark = Color(0xFFC00000)
