/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val cardview: String = "androidx.cardview:cardview:_"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    const val core_ktx: String = "androidx.core:core-ktx:_"

    const val lifecycle_livedata: String = "androidx.lifecycle:lifecycle-livedata:_"

    const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:_"

    const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_rules: String = "androidx.test:rules:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val photoview: String = "com.github.chrisbanes:PhotoView:_"

    const val material_about_library: String =
            "com.github.daniel-stoneuk:material-about-library:_"

    const val switcher: String = "com.github.tukak:Switcher:_"

    const val material: String = "com.google.android.material:material:_"

    const val adapterdelegates4: String = "com.hannesdorfmann:adapterdelegates4:_"

    const val timber: String = "com.jakewharton.timber:timber:_"

    const val iconics_core: String = "com.mikepenz:iconics-core:_"

    const val material_design_iconic_typeface: String =
            "com.mikepenz:material-design-iconic-typeface:_"

    const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    const val picasso: String = "com.squareup.picasso:picasso:_"

    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    const val busybee_android: String = "io.americanexpress.busybee:busybee-android:_"

    const val junit: String = "junit:junit:_"

    const val hamcrest_library: String = "org.hamcrest:hamcrest-library:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    const val koin_android: String = "io.insert-koin:koin-android:_"

    const val koin_test: String = "io.insert-koin:koin-test:_"

    const val mockito_core: String = "org.mockito:mockito-core:_"
}
