import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val cardview: String = "androidx.cardview:cardview:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val lifecycle_livedata: String = "androidx.lifecycle:lifecycle-livedata:_"

    public const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    public const val espresso_contrib: String = "androidx.test.espresso:espresso-contrib:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_rules: String = "androidx.test:rules:_"

    public const val androidx_test_runner: String = "androidx.test:runner:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val photoview: String = "com.github.chrisbanes:PhotoView:_"

    public const val material_about_library: String =
            "com.github.daniel-stoneuk:material-about-library:_"

    public const val switcher: String = "com.github.tukak:Switcher:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val adapterdelegates4: String = "com.hannesdorfmann:adapterdelegates4:_"

    public const val timber: String = "com.jakewharton.timber:timber:_"

    public const val iconics_core: String = "com.mikepenz:iconics-core:_"

    public const val material_design_iconic_typeface: String =
            "com.mikepenz:material-design-iconic-typeface:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val picasso: String = "com.squareup.picasso:picasso:_"

    public const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val busybee_android: String = "io.americanexpress.busybee:busybee-android:_"

    public const val junit: String = "junit:junit:_"

    public const val hamcrest_library: String = "org.hamcrest:hamcrest-library:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:_"

    public const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val koin_android: String = "org.koin:koin-android:_"

    public const val koin_androidx_viewmodel: String = "org.koin:koin-androidx-viewmodel:_"

    public const val koin_test: String = "org.koin:koin-test:_"

    public const val mockito_core: String = "org.mockito:mockito-core:_"
}
