import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_squareup_retrofit2: String = "2.6.2"

    const val androidx_databinding: String = "3.5.1"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val androidx_lifecycle: String = "2.1.0"

    const val androidx_test: String = "1.2.0"

    const val org_koin: String = "2.0.1"

    const val com_android_tools_build_gradle: String = "3.5.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val material_design_iconic_typeface: String = "2.2.0.6-kotlin"

    const val material_about_library: String = "2.4.2"

    const val adapterdelegates4: String = "4.2.0"

    const val constraintlayout: String = "2.0.0-beta2"

    const val hamcrest_library: String = "2.1"

    const val busybee_android: String = "0.0.2"

    const val iconics_core: String = "4.0.1-b02"

    const val mockito_core: String = "3.1.0"

    const val recyclerview: String = "1.0.0"

    const val lint_gradle: String = "26.5.1"

    const val appcompat: String = "1.1.0"

    const val photoview: String = "2.3.0"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.1.0"

    const val material: String = "1.0.0"

    const val switcher: String = "2.4.0"

    const val picasso: String = "2.71828"

    const val okhttp: String = "4.2.2"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.1-5435860"

    const val junit: String = "4.12"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
